### ISSUE TITLE
[AVM Module Issue]: Contradicting variable description

### ISSUE THREAD

**Issue by PetterHL** [Azure/terraform-azurerm-avm-res-desktopvirtualization-workspace#79]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

![Image](https://github.com/user-attachments/assets/0efcedf4-63b4-4d3e-9dca-50071940ea33)

Either change the description, or change the default value.

**Comment by jensheerin** [comment]
@PetterHL Thank you for raising the issue!! Fix applied. Thanks again!
